### ISSUE TITLE
USER STORY : User must provide details required by the restaurant on registration.

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/the-night-garden#10]
Linked Epic: #8 

## Description

As a Site Admin I can require users to provide an email address and their first and last names on registration so that I can contact users if required and can address them by name when contacting them.

## Acceptance Criteria
  
* Acceptance Criteria 1: Users are required to provide an email address on registration for an account.
* Acceptance Criteria 2: Users are required to provide their first and last names on registration for an account.
* 

## Tasks

- [ ] Configure settings to make an account email required.
- [ ] Create a CustomSignUpForm class which extends the Django allauth SignupForm class and create fields for first name and last name.
- [ ] Limit the first and last name fields to 30 characters each.
- [ ] Only allow users to 
- [ ] Task 2
- [ ] Task 3
