### ISSUE TITLE
USER STORY 8: User cannot make more than one booking per date.

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/the-night-garden#13]
Linked Epic: #11 

## Description

As a Site Admin I can prevent a user making more than one booking per day so that large events for one User are within the control of the Site Admin.

## Acceptance Criteria
  
* Acceptance Criteria 1: A user can only make one booking per date.

## Tasks

- [ ] Create a clean date method for the BookingForm.
- [ ] Add functionality so that a user cannot make more than one booking per date.
- [ ] Write unit tests.
- [ ] Test functionality.
