### ISSUE TITLE
USER STORY 9: User cannot make a booking for today for a time in the past

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/the-night-garden#14]
Linked Epic: #11 

## Description

As a Site Admin I can prevent a user making a booking today for a time in the past so that I only receive valid bookings for the restaurant and minimise user error.

## Acceptance Criteria
  
* Acceptance Criteria 1: User can only make a booking for today for a time that is not in the past.
* Acceptance Criteria 2: User will receive an error message if they try to book for a time in the past.
* Acceptance Criteria 3: User's booking is not made.

## Tasks

- [ ] Add clean time method to BookingForm class.
- [ ] Add functionality to prevent a user making a booking for today for a time in the past.
- [ ] Write unit tests.
- [ ] Test functionality.
