### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/the-night-garden#2]
Linked Epic: 

## Description

As a Site Admin I can filter the current restaurant tables, time slots, bookings and registered users so that I can find out specific information that I want about the restaurant and its customers quickly. 

## Acceptance Criteria
  
* Acceptance Criteria 1: The Site Admin has a password protected login for the site allowing them to access the Admin panel.
* Acceptance Criteria 2: The Site Admin can log out of the Admin panel. 
* Acceptance Criteria 3: The Site Admin can view the current restaurant tables. 
* Acceptance Criteria 4: The Site Admin can view the current restaurant time slots. 
* Acceptance Criteria 5: The Site Admin can view the current restaurant bookings. 
* Acceptance Criteria 6: The Site Admin can view the current restaurant users with a registered account. 
* Acceptance Criteria 7: The Site Admin can filter the tables by name or capacity.
* Acceptance Criteria 8: The Site Admin can filter the time slots by time or table. 
* Acceptance Criteria 9: The Site Admin can filter the 

## Tasks

- [ ] Create model for Tables. 
- [ ] Create model for Time Slots.
- [ ] Create model for Bookings. 
- [ ] Register models in Admin.py
