### ISSUE TITLE
USER STORY 22: Site Menu Information.

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/the-night-garden#28]
Linked Epic: #25 

## Description

As a Site User I can view and download the menus for the restaurant so that I know if I want to register with the site to book a table and eat there.

## Acceptance Criteria
  
* Acceptance Criteria 1: User does not have to have created an account or logged in to navigate to the Menus page.
* Acceptance Criteria 2: User can click on a link to the Summer Menu which opens a pdf in a new tab.
* Acceptance Criteria 3: User can click on a link to the Winter Menu which opens a pdf in a new tab.
* Acceptance Criteria 4: User receives feedback on whether they are hovering over or focussing on the applicable link with a colour change.

## Tasks

- [ ] Create pdf Summer and Winter menus.
- [ ] Include links to the Menus in the menus.html template.
- [ ] Ensure that links open up in a new tab.
- [ ] Ensure that menus can be viewed when the links are clicked on.
- [ ] Implement link colour change when hovering over/focussing on the links.
- [ ] Test implementation.
