### ISSUE TITLE
USER STORY 1: Admin Management of Restaurant Tables

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/the-night-garden#4]
Linked Epic: #3 

## Description

As a Site Admin I can create, read, update, delete and filter the restaurant tables so that I can manage the size and number of tables available for guests to book. 

## Acceptance Criteria
  
* Acceptance Criteria 1: The Site Admin has a password protected login for the site, allowing them to access the Admin panel.
* Acceptance Criteria 2: The Site Admin can create available restaurant tables. Table names should be limited to 15 characters and table sizes limited to a choice of 2, 4, 6 or 8 as these are the table sizes the restaurant has purchased. 
* Acceptance Criteria 3: The Site Admin can see the available restaurant table names and sizes and search and filter these by name or size.
* Acceptance Criteria 4: The Site Admin can only create unique table names.
* Acceptance Criteria 5: The Site Admin can amend the name and/or size of the tables. 
* Acceptance Criteria 6: The Site Admin can delete the tables (but it is accepted by the restaurant that they will not do this without firstly manually seeing if other table(s) are available to change existing bookings' table(s) or as a last resort manually contacting guests to let them know that their associated booking will be cancelled prior to deleting the applicable table).

## Tasks

- [ ] Create Table model ensuring table names are limited to 15 characters, table sizes are limited to a choice of 2, 4, 6 or 8, table names are unique and tables are ordered by ascending table size and migrate changes to the database.
- [ ] Create superuser account for Admin user and check that Admin can log in and out to see the Admin panel. 
- [ ] Create TableAdmin class to display table names and sizes in the Admin panel and allow filtering and searching according to table names and sizes.
- [ ] Write unit tests.
- [ ] Test the functionality.
